name: archiman
description: A simple project to show preferred architecture.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  kt_dart: ^0.10.0
  logging: ^1.0.2
  universal_io: ^2.0.4
  intl: ^0.17.0

  # Firebase
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_analytics: ^9.1.9

  # UI
  auto_localized: ^1.3.0
  device_preview: ^1.0.0

  # Services
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  auto_localized_generator: ^1.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_android: "resources/app_icon/app_icon_android.png"
  image_path_ios: "resources/app_icon/app_icon_ios.png"

# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#F6F6F6"

# Spider used to generate asset fields
# spider create
# spider build --watch
